Algoritmo "somador com repita"
// USANDO O "REPITA" PARA FAZER AS SOMAS

Var
  N, s: inteiro
  resp: caractere

Inicio
      s <- 0
      repita
               escreva("Digite o valor ==> ")
               leia(N)
               s <- s + n
               escreva("Você quer continuar? [S/N] ")
               leia(resp)
               
      ate (resp = "N")
      escreval("A soma de todos os números é ", s)

Fimalgoritmo