Algoritmo "Partida de Futebol"

Var
   t1,  t2: inteiro

Inicio
      escreva("Quantos gols Corinthians fez? ")
      leia (t1)
      escreva("Quantos gols São Paulo fez? ")
      leia(t2)
      se (t1 = t2) entao
         escreva("Empate")
      senao
           se (t1 < 2) e (t2 >= 2) e (t2 < 4) entao
              escreva("
              escreva(" Jogo normal")
           senao
                se (t1
           fimse
      fimse
      

Fimalgoritmo